name: ML_and_AI_Challenges
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - jupyterlab-server
  - jupyterlab-widgets
  - ipywidgets
  - nbconvert
  - nbformat
  - notebook
  - ipykernel
  - ipython
  - ipython-genutils
  - ipydatawidgets
  - ipyevents
  - ipyfilechooser
  - ipytree
  - ipywebrtc
  - ipywidgets
  - torch
  - torchvision
  - tensorflow
  - keras
  - keras-tuner
  - scikit-image
  - xgboost
  - lightgbm
  - catboost
  - plotly
  - dash
  - boto3
  - sageMaker
  - kaggle
  - geopandas